* dans has_excludes(), ne selectionne que les sous-(volumes|repertoires)  * ne force pas le rollback si pas -B  * pas de redirection 2>&1 sur la commande distante + -T pour ssh  * make_source_snapshot() supprimait les mauvais snapshots (lie a has_excludes() mais pas que)  * message plus clair si une destination existante est sensee etre exclue  * CheckHostIp=no pour ssh si -T  * creation de la destination simplifiee  * Creation d'un code de retour '7' si -j peut etre tente  * Ne corrige pas les mountpoints=legacy ou none  * Supprime systematiquement les vieux snapshots inutiles si tout s'est bien passe + corrections

diff --git a/lib/zfs_sync_vol b/lib/zfs_sync_vol
--- a/lib/zfs_sync_vol
+++ b/lib/zfs_sync_vol
@@ -14,8 +14,6 @@
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
 
 # VARIABLES that change things: (no options for those ones)
-# - CLEANOLDSNAPSTOO : will clean ancien snapshots 
-#   from src to dst in this volume
 # - CHANGEDSTHOST <oldname> : will use oldname to search snapshots
 #   (and clean them)
 # - SSH_CIPHERS : list of preferred ssh ciphers (ssh -c)
@@ -98,7 +96,7 @@ do
       RECURSE="YES_RECURSE"
       ROLLBACKOPT="-Rf"
       #ROLLBACKOPT="-r"
-      DOROLLBACK=1
+      DOROLLBACK="LOOSELY"
       RECVOPT='-F'
     ;;
     B)
@@ -183,11 +181,17 @@ done
 shift $(expr $OPTIND - 1)
 
 erreur() {
+  case $1 in
+    [0-9])
+      ret=$1
+      shift
+    ;;
+  esac
   echo $* 1>&2
   if [ ! -z "$SYSLOG_ID" ] && [ "$SYSLOG_ID" != "none" ]; then
     logger -p ${SYSLOG_ID}.error -t "${0##*/}["$$"]" -- $@
   fi
-  exit 1
+  exit ${ret:-1}
 }
 
 inform() {
@@ -216,9 +220,11 @@ missingvol() {
 has_excludes() {
   test -s "$EXCLUDEFILE" || return 1
   # excludes as zfs path
-  grep '^'$1 $EXCLUDEFILE && r=0
+  grep '^'$1'/.*' $EXCLUDEFILE && r=0
   # excludes as unix path
-  grep '^'$(src_zfs_list | grep '^'$1'!' | cut -d'!' -f2) $EXCLUDEFILE && r=0
+  for efs in $(src_zfs_list | grep '^'$1'/[^@]*!' | cut -d'!' -f2 | sort); do 
+    grep "^$efs$" $EXCLUDEFILE && r=0
+  done
   return ${r:-1}
 }
 
@@ -237,7 +243,7 @@ dst_run() {
   if [ -t 0 ]; then
     $dstcmd "$@"
   else
-    $dstcmd "$@" 2>&1
+    $dstcmd "$@"
   fi
 }
 
@@ -245,7 +251,7 @@ src_run() {
   if [ -t 0 ]; then
     $srccmd $@
   else
-    $srccmd $@ 2>&1
+    $srccmd $@
   fi
 }
 
@@ -269,14 +275,15 @@ dst_zfs_list() {
 # args: dstvol
 make_source_snapshot() {
   DELSNAPS=""
+  # build list of snapshots to be deleted before
   if has_excludes ${1%@*} > /dev/null; then
-    for fs in $(src_zfs_list | cut -d'!' -f1 | grep '^'${1%@*}'/[^/]*$'); do
+    for fs in $(src_zfs_list | cut -d'!' -f1 | grep '^'${1%@*}'/[^@]*$'); do
       if is_excluded $fs; then
         if [ "$RECURSE" != "YES_RECURSE" ] || ! echo $DELSNAPS | grep -q ' '$fs' '; then
-          DELSNAPS=$DELSNAPS"$fs@${1#*@} "
+          DELSNAPS=$DELSNAPS"${fs}@${1#*@} "
         fi
       else
-        for sfs in $(has_excludes $fs); do
+        for sfs in $(has_excludes $fs | sort -r); do
           DELSNAPS=$DELSNAPS"$sfs@${1#*@} "
         done
       fi
@@ -310,7 +317,9 @@ get_last_common_snapshot() {
       for dstfs in $(dst_zfs_list | cut -d'!' -f1 | grep '^'${DSTVOL}'/[^@]*$'); do
         if ! dst_zfs_list | cut -d'!' -f1 | grep -q '^'$dstfs'@'${snapcandidate}'$'; then
           if is_excluded ${SRCVOL}${dstfs#$DSTVOL}; then
-            warne "excluded fs existing on dest: $dstfs"
+            warne "excluded fs existing on dest: $dstfs : delete ?"
+#            dst_cmd "zfs destroy -r $dstfs"
+            rm $DSTZFSLIST
           else
             warne "snapshot ${snapcandidate} missing on $dstfs"
             snapcandidate=""
@@ -350,8 +359,8 @@ rollback_to_last_common_snapshot() {
 }
 
 # sanity check args
-if [ ! -z "$SRCPRESNAPFORMAT" ] && [ "$SNAPOPT" != "-I" -o ! -z "$DOROLLBACK" ]; then
-  warne "$0: -m is incompatible with -B, and needs -I to get the snapshot"
+if [ ! -z "$SRCPRESNAPFORMAT" ] && [ "$SNAPOPT" != "-I" ]; then
+  warne "$0: -m needs -I to get the snapshot"
   exec $0 -0
 fi
 if [ ! -z "$TRANSPORT_CMD" ] && [ -z "$TRANSPORT_SRC_OPTS" -o -z "$TRANSPORT_DST_OPTS" ]; then
@@ -391,7 +400,7 @@ SYSLOG_ID=${SYSLOG_ID:-user}
 ####################
 ### process args ###
 ####################
-SSHOPTS=${SSHKEY:+"-i $SSHKEY"}${TEMPSSH:+" -o \"UserKnownHostsFile ${TMPDIR:-/tmp}/kkk\""}${SSH_CIPHERS:+" -c $SSH_CIPHERS"}
+SSHOPTS="-T"${SSHKEY:+" -i $SSHKEY"}${TEMPSSH:+" -o \"UserKnownHostsFile ${TMPDIR:-/tmp}/kkk\" -o \"CheckHostIP no\""}${SSH_CIPHERS:+" -c $SSH_CIPHERS"}
 
 # determine source and dest hosts, volumes,...
 SRCHOST=""
@@ -441,7 +450,7 @@ if [ ! -z "$TRANSPORT_CMD" ]; then
 else
   # try mbuffer
   MBUFFER_SRC_CMD=$($srcrocmd "which mbuffer | fgrep -v 'not found'")
-  [ ! -z "$MBUFFER_SRC_CMD" ] && MBUFFER_SRC_CMD=$MBUFFER_SRC_CMD" -m 512M -q"
+  [ ! -z "$MBUFFER_SRC_CMD" ] && MBUFFER_SRC_CMD=$MBUFFER_SRC_CMD" -m 64M -q"
   MBUFFER_DST_CMD=$($srcrocmd "which mbuffer | fgrep -v 'not found'")
   [ ! -z "$MBUFFER_DST_CMD" ] && MBUFFER_DST_CMD=$MBUFFER_DST_CMD" -m 1G -q"
 fi
@@ -457,19 +466,23 @@ fi
 
 DSTMOUNTBASE=$(dst_zfs_list | grep '^'${DSTVOL}'!' | cut -d'!' -f2)
 
-# create destination if needed && -C and not -B | -R
-if [ -z "$DSTMOUNTBASE" ] && [ "$DOROLLBACK" != "YES_ROLLBACK" -a "$CREATEDEST" = "YES_CREATEDEST" -a "$RECURSE" != "YES_RECURSE" ]; then
-  cmd="zfs create"
-  $srcrocmd "zfs get -H -oproperty,value,source all ${SRCVOL} | grep 'local$'" | while read prop val source; do
-      if [ "$prop" = "mountpoint" -a "$val" != "none" -a "$val" != "legacy" ]; then
-        cmd="$cmd -o orig:mountpoint=$val"
-      else
-        cmd="$cmd -o $prop=$val";
-      fi
-    done
-  dst_run "$cmd ${DSTVOL}" || missingvol ${DST:+$DST}
-  rm $DSTZFSLIST
-  DSTMOUNTBASE=$(dst_zfs_list | grep '^'${DSTVOL}'!' | cut -d'!' -f2)
+# create destination if needed && -C
+if [ -z "$DSTMOUNTBASE" ]; then
+  if [ "$CREATEDEST" = "YES_CREATEDEST" ]; then
+    cmd="zfs create"
+    $srcrocmd "zfs get -H -oproperty,value,source all ${SRCVOL} | grep 'local$'" | while read prop val source; do
+        if [ "$prop" = "mountpoint" -a "$val" != "none" -a "$val" != "legacy" ]; then
+          cmd="$cmd -o orig:mountpoint=$val"
+        else
+          cmd="$cmd -o $prop=$val";
+        fi
+      done
+    dst_run "$cmd ${DSTVOL}" || missingvol ${DST:+$DST}
+    rm $DSTZFSLIST
+    DSTMOUNTBASE=$(dst_zfs_list | grep '^'${DSTVOL}'!' | cut -d'!' -f2)
+  else
+    erreur "La destination (${DSTVOL}) n'existe pas et pas -C :("
+  fi
 fi
 
 # check for dangerous new fixed mountpoints on source for new volumes
@@ -489,7 +502,10 @@ if ! dst_zfs_list | grep -Ev '^'${DSTVOL}'.*!(none|legacy)!' | grep -qv '!'${DST
 fi
 
 # locate last snapshot (if any)
-get_last_common_snapshot
+if ! get_last_common_snapshot && dst_zfs_list | grep -q '^'${DSTVOL}'@'; then
+  # If no common snapshot AND DSTVOL has snapshots, zfs receive would fail.
+  erreur 7 "ERREUR: des snapshots existent dans ${DSTVOL} et aucun snapshot commun existant n'a ete trouve... Re-essayez avec -j ou supprimez tout ${DSTVOL}"
+fi
 
 TCHECKSOK=$(date +%s)
 TCHECKS=$(($TCHECKSOK - $TBEGIN))
@@ -522,8 +538,8 @@ TMKSNAP=$(($TMKSNAPOK - $TCHECKSOK))
 DONE=0
 DSTSNAPSTODEL=""
 
-SRC_SEND_CMD="zfs send ${SENDOPT} ${LASTCOMMONSNAP:+$INCOPT $LASTCOMMONSNAP} ${SRCVOL}@${NEWSNAP}${MBUFFER_SRC_CMD:+ | $MBUFFER_SRC_CMD}"
-DST_REVC_CMD="${MBUFFER_DST_CMD:+$MBUFFER_DST_CMD | }zfs receive -v ${RECVOPT}${NODSTMOUNT:+ -u} ${DSTVOL}"
+SRC_SEND_CMD="zfs send ${SENDOPT} ${LASTCOMMONSNAP:+$INCOPT $LASTCOMMONSNAP} ${SRCVOL}@${NEWSNAP}"
+DST_REVC_CMD="zfs receive -v ${RECVOPT}${NODSTMOUNT:+ -u} ${DSTVOL}"
 inform "Sending ${SRCVOL}@${NEWSNAP}${MBUFFER_SRC_CMD:+ with mbuffer}${TRANSPORT_CMD:+ via TRANSPORT_CMD}"
 if [ ! -z "$TRANSPORT_CMD" ]; then
   src_run "$SRC_SEND_CMD | $TRANSPORT_SRC_CMD $TRANSPORT_SRC_OPTS" &
@@ -532,12 +548,14 @@ if [ ! -z "$TRANSPORT_CMD" ]; then
   wait
   RET=$?
 else
-  src_run "$SRC_SEND_CMD" | dst_run "$DST_REVC_CMD"
+  src_run "$SRC_SEND_CMD ${MBUFFER_SRC_CMD:+ | $MBUFFER_SRC_CMD}" | dst_run "${MBUFFER_DST_CMD:+$MBUFFER_DST_CMD | }$DST_REVC_CMD"
   RET=$?
 fi
 if [ $RET -ne 0 ]; then
   if [ -z "$DOROLLBACK" ]; then
-    warne "Warning transfering from ${SRCHOST:+"$SRCHOST:"}${SRCVOL}@${NEWSNAP} to ${DSTHOST:+"$DSTHOST:"}${DSTVOL}${LASTCOMMONSNAP:+" (inc. based on @$LASTCOMMONSNAP)"}. zfs returns $RET"
+    warne "Error transfering from ${SRCHOST:+"$SRCHOST:"}${SRCVOL}@${NEWSNAP} to ${DSTHOST:+"$DSTHOST:"}${DSTVOL}${LASTCOMMONSNAP:+" (inc. based on @$LASTCOMMONSNAP)"}. zfs returns $RET"
+    warne "  send command $SRC_SEND_CMD"
+    warne "  receive command $SRC_SEND_CMD"
     warne "you may retry with -B (rollback forced) and/or -j (loosy snapshot search)"
     SRCSNAPSTODEL=$SRCSNAPSTODEL${NEWSNAP:+" ${SRCVOL}@${NEWSNAP}"}
     DSTSNAPSTODEL=$DSTSNAPSTODEL${NEWSNAP:+" ${DSTVOL}@${NEWSNAP}"}
@@ -554,9 +572,11 @@ TTRANSFER=$(($TTRANSFEROK - $TMKSNAPOK))
 if [ -z "$DSTREMOUNTORIG" -a ! -z "$CORRECTMOUNTS" ]; then
   inform "Enregistrement+modification des points de montage originaux sur ${DSTVOL}"
   dst_run 'zfs get -Hp -r -t filesystem -oname,value,source mountpoint '${DSTVOL}' | grep 'received$' | while read vol val src; do
+    if [ "$val" != "legacy" ] && [ "$val" != "none" ]; then
       zfs inherit mountpoint $vol
       zfs set orig:mountpoint=$val $vol
-    done'
+    fi
+  done'
 fi
 
 # si restauration, on remet les points de montage originaux
@@ -573,15 +593,17 @@ fi
 TPOSTCHECKSOK=$(date +%s)
 TPOSTCHECKS=$(($TPOSTCHECKSOK - $TTRANSFEROK))
 
-if [ ! -z "$CLEANOLDSNAPSTOO" -a $RET -eq 0 ]; then
+if [ -z "$KEEPSRCSNAPS" -a $RET -eq 0 ]; then
   SRCSNAPSTODEL=$SRCSNAPSTODEL$(src_zfs_list | cut -d'!' -f1 | \
     grep -E '@'${SRCSNAPHOST:-$MYNAME}'-'${DSTSEARCHHOST:-$MYNAME}'-[[:digit:]]{8}-[[:digit:]]{2}h[[:digit:]]{2}m[[:digit:]]{2}s$' | \
-    fgrep -v $LASTCOMMONSNAP | fgrep -v $NEWSNAP | \
-    while read s; do is_excluded ${s%@*} || echo " $s"; done)
+    grep -Fv $LASTCOMMONSNAP | fgrep -v $NEWSNAP | \
+    while read s; do if ! is_excluded ${s%@*} && [ "${s#*@}" != "$LASTCOMMONSNAP" ] && [ "${s#*@}" != "$NEWSNAP" ]; then echo " $s"; fi; done)
+fi
+if [ -z "$KEEPDSTSNAPS" -a $RET -eq 0 ]; then
   DSTSNAPSTODEL=$DSTSNAPSTODEL$(dst_zfs_list | cut -d'!' -f1 | \
     grep -E '@'${SRCSNAPHOST:-$MYNAME}'-'${DSTSEARCHHOST:-$MYNAME}'-[[:digit:]]{8}-[[:digit:]]{2}h[[:digit:]]{2}m[[:digit:]]{2}s$' | \
     fgrep -v $LASTCOMMONSNAP | fgrep -v $NEWSNAP | \
-    while read s; do is_excluded ${s%@*} || echo " $s"; done)
+    while read s; do if ! is_excluded ${s%@*} && [ "${s#*@}" != "$LASTCOMMONSNAP" ] && [ "${s#*@}" != "$NEWSNAP" ]; then echo " $s"; fi; done)
 fi
 if [ ! -z "$SRCSNAPSTODEL" ]; then
   inform "Cleaning snapshots${SRCHOST:+ on $SRCHOST}: $SRCSNAPSTODEL" 
